type Country = {
  id: number;
  countryName: string;
  code: string;
};
export const countries: Country[] = [
  { id: 1, countryName: "Afghanistan", code: "AF" },
  { id: 2, countryName: "Albania", code: "AL" },
  { id: 3, countryName: "Algeria", code: "DZ" },
  { id: 4, countryName: "Andorra", code: "AD" },
  { id: 5, countryName: "Angola", code: "AO" },
  { id: 6, countryName: "Antigua and Barbuda", code: "AG" },
  { id: 7, countryName: "Argentina", code: "AR" },
  { id: 8, countryName: "Armenia", code: "AM" },
  { id: 9, countryName: "Australia", code: "AU" },
  { id: 10, countryName: "Austria", code: "AT" },
  { id: 11, countryName: "Azerbaijan", code: "AZ" },
  { id: 12, countryName: "Bahamas", code: "BS" },
  { id: 13, countryName: "Bahrain", code: "BH" },
  { id: 14, countryName: "Bangladesh", code: "BD" },
  { id: 15, countryName: "Barbados", code: "BB" },
  { id: 16, countryName: "Belarus", code: "BY" },
  { id: 17, countryName: "Belgium", code: "BE" },
  { id: 18, countryName: "Belize", code: "BZ" },
  { id: 19, countryName: "Benin", code: "BJ" },
  { id: 20, countryName: "Bhutan", code: "BT" },
  { id: 21, countryName: "Bolivia", code: "BO" },
  { id: 22, countryName: "Bosnia and Herzegovina", code: "BA" },
  { id: 23, countryName: "Botswana", code: "BW" },
  { id: 24, countryName: "Brazil", code: "BR" },
  { id: 25, countryName: "Brunei", code: "BN" },
  { id: 26, countryName: "Bulgaria", code: "BG" },
  { id: 27, countryName: "Burkina Faso", code: "BF" },
  { id: 28, countryName: "Burundi", code: "BI" },
  { id: 29, countryName: "Cabo Verde", code: "CV" },
  { id: 30, countryName: "Cambodia", code: "KH" },
  { id: 31, countryName: "Cameroon", code: "CM" },
  { id: 32, countryName: "Canada", code: "CA" },
  { id: 33, countryName: "Central African Republic", code: "CF" },
  { id: 34, countryName: "Chad", code: "TD" },
  { id: 35, countryName: "Chile", code: "CL" },
  { id: 36, countryName: "China", code: "CN" },
  { id: 37, countryName: "Colombia", code: "CO" },
  { id: 38, countryName: "Comoros", code: "KM" },
  { id: 39, countryName: "Congo, Democratic Republic of the", code: "CD" },
  { id: 40, countryName: "Congo, Republic of the", code: "CG" },
  { id: 41, countryName: "Costa Rica", code: "CR" },
  { id: 42, countryName: "Cote d'Ivoire", code: "CI" },
  { id: 43, countryName: "Croatia", code: "HR" },
  { id: 44, countryName: "Cuba", code: "CU" },
  { id: 45, countryName: "Cyprus", code: "CY" },
  { id: 46, countryName: "Czech Republic", code: "CZ" },
  { id: 47, countryName: "Denmark", code: "DK" },
  { id: 48, countryName: "Djibouti", code: "DJ" },
  { id: 49, countryName: "Dominica", code: "DM" },
  { id: 50, countryName: "Dominican Republic", code: "DO" },
  { id: 51, countryName: "Ecuador", code: "EC" },
  { id: 52, countryName: "Egypt", code: "EG" },
  { id: 53, countryName: "El Salvador", code: "SV" },
  { id: 54, countryName: "Equatorial Guinea", code: "GQ" },
  { id: 55, countryName: "Eritrea", code: "ER" },
  { id: 56, countryName: "Estonia", code: "EE" },
  { id: 57, countryName: "Eswatini", code: "SZ" },
  { id: 58, countryName: "Ethiopia", code: "ET" },
  { id: 59, countryName: "Fiji", code: "FJ" },
  { id: 60, countryName: "Finland", code: "FI" },
  { id: 61, countryName: "France", code: "FR" },
  { id: 62, countryName: "Gabon", code: "GA" },
  { id: 63, countryName: "Gambia", code: "GM" },
  { id: 64, countryName: "Georgia", code: "GE" },
  { id: 65, countryName: "Germany", code: "DE" },
  { id: 66, countryName: "Ghana", code: "GH" },
  { id: 67, countryName: "Greece", code: "GR" },
  { id: 68, countryName: "Grenada", code: "GD" },
  { id: 69, countryName: "Guatemala", code: "GT" },
  { id: 70, countryName: "Guinea", code: "GN" },
  { id: 71, countryName: "Guinea-Bissau", code: "GW" },
  { id: 72, countryName: "Guyana", code: "GY" },
  { id: 73, countryName: "Haiti", code: "HT" },
  { id: 74, countryName: "Honduras", code: "HN" },
  { id: 75, countryName: "Hungary", code: "HU" },
  { id: 76, countryName: "Iceland", code: "IS" },
  { id: 77, countryName: "India", code: "IN" },
  { id: 78, countryName: "Indonesia", code: "ID" },
  { id: 79, countryName: "Iran", code: "IR" },
  { id: 80, countryName: "Iraq", code: "IQ" },
  { id: 81, countryName: "Ireland", code: "IE" },
  { id: 82, countryName: "Israel", code: "IL" },
  { id: 83, countryName: "Italy", code: "IT" },
  { id: 84, countryName: "Jamaica", code: "JM" },
  { id: 85, countryName: "Japan", code: "JP" },
  { id: 86, countryName: "Jordan", code: "JO" },
  { id: 87, countryName: "Kazakhstan", code: "KZ" },
  { id: 88, countryName: "Kenya", code: "KE" },
  { id: 89, countryName: "Kiribati", code: "KI" },
  { id: 90, countryName: "Korea, North", code: "KP" },
  { id: 91, countryName: "Korea, South", code: "KR" },
  { id: 92, countryName: "Kosovo", code: "XK" },
  { id: 93, countryName: "Kuwait", code: "KW" },
  { id: 94, countryName: "Kyrgyzstan", code: "KG" },
  { id: 95, countryName: "Laos", code: "LA" },
  { id: 96, countryName: "Latvia", code: "LV" },
  { id: 97, countryName: "Lebanon", code: "LB" },
  { id: 98, countryName: "Lesotho", code: "LS" },
  { id: 99, countryName: "Liberia", code: "LR" },
  { id: 100, countryName: "Libya", code: "LY" },
  { id: 101, countryName: "Liechtenstein", code: "LI" },
  { id: 102, countryName: "Lithuania", code: "LT" },
  { id: 103, countryName: "Luxembourg", code: "LU" },
  { id: 104, countryName: "Madagascar", code: "MG" },
  { id: 105, countryName: "Malawi", code: "MW" },
  { id: 106, countryName: "Malaysia", code: "MY" },
  { id: 107, countryName: "Maldives", code: "MV" },
  { id: 108, countryName: "Mali", code: "ML" },
  { id: 109, countryName: "Malta", code: "MT" },
  { id: 110, countryName: "Marshall Islands", code: "MH" },
  { id: 111, countryName: "Mauritania", code: "MR" },
  { id: 112, countryName: "Mauritius", code: "MU" },
  { id: 113, countryName: "Mexico", code: "MX" },
  { id: 114, countryName: "Micronesia", code: "FM" },
  { id: 115, countryName: "Moldova", code: "MD" },
  { id: 116, countryName: "Monaco", code: "MC" },
  { id: 117, countryName: "Mongolia", code: "MN" },
  { id: 118, countryName: "Montenegro", code: "ME" },
  { id: 119, countryName: "Morocco", code: "MA" },
  { id: 120, countryName: "Mozambique", code: "MZ" },
  { id: 121, countryName: "Myanmar", code: "MM" },
  { id: 122, countryName: "Namibia", code: "NA" },
  { id: 123, countryName: "Nauru", code: "NR" },
  { id: 124, countryName: "Nepal", code: "NP" },
  { id: 125, countryName: "Netherlands", code: "NL" },
  { id: 126, countryName: "New Zealand", code: "NZ" },
  { id: 127, countryName: "Nicaragua", code: "NI" },
  { id: 128, countryName: "Niger", code: "NE" },
  { id: 129, countryName: "Nigeria", code: "NG" },
  { id: 130, countryName: "North Macedonia", code: "MK" },
  { id: 131, countryName: "Norway", code: "NO" },
  { id: 132, countryName: "Oman", code: "OM" },
  { id: 133, countryName: "Pakistan", code: "PK" },
  { id: 134, countryName: "Palau", code: "PW" },
  { id: 135, countryName: "Panama", code: "PA" },
  { id: 136, countryName: "Papua New Guinea", code: "PG" },
  { id: 137, countryName: "Paraguay", code: "PY" },
  { id: 138, countryName: "Peru", code: "PE" },
  { id: 139, countryName: "Philippines", code: "PH" },
  { id: 140, countryName: "Poland", code: "PL" },
  { id: 141, countryName: "Portugal", code: "PT" },
  { id: 142, countryName: "Qatar", code: "QA" },
  { id: 143, countryName: "Romania", code: "RO" },
  { id: 144, countryName: "Russia", code: "RU" },
  { id: 145, countryName: "Rwanda", code: "RW" },
  { id: 146, countryName: "Saint Kitts and Nevis", code: "KN" },
  { id: 147, countryName: "Saint Lucia", code: "LC" },
  { id: 148, countryName: "Saint Vincent and the Grenadines", code: "VC" },
  { id: 149, countryName: "Samoa", code: "WS" },
  { id: 150, countryName: "San Marino", code: "SM" },
  { id: 151, countryName: "Sao Tome and Principe", code: "ST" },
  { id: 152, countryName: "Saudi Arabia", code: "SA" },
  { id: 153, countryName: "Senegal", code: "SN" },
  { id: 154, countryName: "Serbia", code: "RS" },
  { id: 155, countryName: "Seychelles", code: "SC" },
  { id: 156, countryName: "Sierra Leone", code: "SL" },
  { id: 157, countryName: "Singapore", code: "SG" },
  { id: 158, countryName: "Slovakia", code: "SK" },
  { id: 159, countryName: "Slovenia", code: "SI" },
  { id: 160, countryName: "Solomon Islands", code: "SB" },
  { id: 161, countryName: "Somalia", code: "SO" },
  { id: 162, countryName: "South Africa", code: "ZA" },
  { id: 163, countryName: "South Sudan", code: "SS" },
  { id: 164, countryName: "Spain", code: "ES" },
  { id: 165, countryName: "Sri Lanka", code: "LK" },
  { id: 166, countryName: "Sudan", code: "SD" },
  { id: 167, countryName: "Suriname", code: "SR" },
  { id: 168, countryName: "Sweden", code: "SE" },
  { id: 169, countryName: "Switzerland", code: "CH" },
  { id: 170, countryName: "Syria", code: "SY" },
  { id: 171, countryName: "Taiwan", code: "TW" },
  { id: 172, countryName: "Tajikistan", code: "TJ" },
  { id: 173, countryName: "Tanzania", code: "TZ" },
  { id: 174, countryName: "Thailand", code: "TH" },
  { id: 175, countryName: "Timor-Leste", code: "TL" },
  { id: 176, countryName: "Togo", code: "TG" },
  { id: 177, countryName: "Tonga", code: "TO" },
  { id: 178, countryName: "Trinidad and Tobago", code: "TT" },
  { id: 179, countryName: "Tunisia", code: "TN" },
  { id: 180, countryName: "Turkey", code: "TR" },
  { id: 181, countryName: "Turkmenistan", code: "TM" },
  { id: 182, countryName: "Tuvalu", code: "TV" },
  { id: 183, countryName: "Uganda", code: "UG" },
  { id: 184, countryName: "Ukraine", code: "UA" },
  { id: 185, countryName: "United Arab Emirates", code: "AE" },
  { id: 186, countryName: "England", code: "Eng" },
  { id: 187, countryName: "United States", code: "US" },
  { id: 188, countryName: "Uruguay", code: "UY" },
  { id: 189, countryName: "Uzbekistan", code: "UZ" },
  { id: 190, countryName: "Vanuatu", code: "VU" },
  { id: 191, countryName: "Vatican City", code: "VA" },
  { id: 192, countryName: "Venezuela", code: "VE" },
  { id: 193, countryName: "Vietnam", code: "VN" },
  { id: 194, countryName: "Yemen", code: "YE" },
  { id: 195, countryName: "Zambia", code: "ZM" },
  { id: 196, countryName: "Zimbabwe", code: "ZW" },
  { id: 197, countryName: "Scotland", code: "Sco" },
  { id: 198, countryName: "Wales", code: "Wal" },
  { id: 199, countryName: "Northern Ireland", code: "Nor" },
  { id: 200, countryName: "Bermuda", code: "Ber" },
];
