
export const clubDisplayNames: Record<string, string> = {
    DRIVER: "Driver",
    THREE_WOOD: "3 Wood",
    SEVEN_WOOD: "7 Wood",
    NINE_WOOD: "9 Wood",
    TWO_HYBRID: "2 Hybrid",
    THREE_HYBRID: "3 Hybrid",
    FOUR_HYBRID: "4 Hybrid",
    FIVE_HYBRID: "5 Hybrid",
    TWO_IRON: "2 Iron",
    THREE_IRON: "3 Iron",
    FOUR_IRON: "4 Iron",
    FIVE_IRON: "5 Iron",
    SIX_IRON: "6 Iron",
    SEVEN_IRON: "7 Iron",
    EIGHT_IRON: "8 Iron",
    NINE_IRON: "9 Iron",
    PW: "P Wedge",
    GW: "G Wedge",
    SW: "S Wedge",
    LW: "L Wedge",
    AW: "A Wedge",
};