[dependencies]
base = "0.10.4"

[package]
name = "itertools"
version = "0.2.1"
description = "A library with utility functions and data types for creating efficient iterators in Motoko."
repository = "https://github.com/NatLabs/Itertools"
license = "MIT"
